### ISSUE TITLE
Deoplete throws error when trying to manually trigger complete popup

### ISSUE THREAD

**Issue by lriuui0x0** [Shougo/deoplete.nvim#1079]
# Problems summary

I would like to only trigger autocomplete popup when I explicitly hit `<C-n>`, but let the suggestions refresh itself as I type. I configured some key mappings and auto-commands, but it's not working and deoplete throws an error on some filetypes (vimscript).

## Expected

Only show autocomplete popup when I explicitly hit `<C-n>`, then let suggestions refresh as I type.

## Environment Information

 * deoplete version (SHA1): Should be the latest, just updated with `:PlugUpdate`

 * OS: Ubuntu

 * neovim `:version` output: `v0.5.0-nightly-1-gdc0e534`

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```
set completeopt=menu,menuone,noinsert
set pumheight=20
let g:deoplete#enable_at_startup = 1
" TODO: Display popup only when explicitly called
call deoplete#custom#option('auto_complete_popup', 'manual')
inoremap <expr> <C-n> g:deoplete#complete()
inoremap <expr> <C-p> g:deoplete#complete()
autocmd TextChangedP * call g:deoplete#complete()
call deoplete#custom#option('sources', { 'c': ['clangx'], 'cpp': ['clangx'], 'python': ['jedi'], '_': ['omni']} )
call deoplete#custom#var('clangx', 'clang_binary', '/usr/local/bin/clang')

```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Open a cpp file, `<C-n>` doesn't show autocomplete popup.
2. Open vimscript file, `<C-n>` generates the following error.
```
Error detected while processing function deoplete#mapping#_complete[1]..<SNR>93_check_completion_info:
line   13:
E716: Key not present in Dictionary: complete_position - 1]
Error detected while processing function deoplete#mapping#_complete[1]..<SNR>93_check_completion_info:
line   13:
E15: Invalid expression: getline('.')[: g:deoplete#_context.complete_position - 1]

```

## Screenshot (if possible)

![Screenshot from 2020-03-07 14-33-39](https://user-images.githubusercontent.com/33423526/76145361-b8290d80-6080-11ea-9e8a-e5af52247c6e.png)

**Comment by Shougo** [comment]
> Only show autocomplete popup when I explicitly hit <C-n>, then let suggestions refresh as I type.

I have implemented the feature.
Please use the latest version.

**Comment by lriuui0x0** [comment]
@Shougo Thanks for your update! However, I found two problems after I updated the plugin.

1) When I bind `<C-n>` with `inoremap <expr> <C-n> g:deoplete#complete()`, and setting `clangx` as the only source for cpp files. If I open an empty cpp file, hit `<C-n>` in insert mode, I get the same error in the screenshot.

2) When I hit `<C-n>` and the popup appears, it doesn't automatically modify the input to its first suggestion (even when the first suggestion is highlighted). And when I hit `<C-n>` again, it modifies the input to the second suggestion. Which basically means I have to `<C-p>` back to get the first suggestion inserted.

I'd happy to provide more information on these issues if you find the description is not clear enough.

BTW, I saw deoplete is developed with python remote plugins. I'm also playing with python remote plugins, can I ask what's a good way to reload the remote plugins after you change the python code? Right now I have to restart vim every time I make some changes which is not very good.

**Comment by Shougo** [comment]
> BTW, I saw deoplete is developed with python remote plugins. I'm also playing with python remote plugins, can I ask what's a good way to reload the remote plugins after you change the python code? Right now I have to restart vim every time I make some changes which is not very good.

You need to restart the editor.  No magic.
I restart neovim repeatedly.

**Comment by Shougo** [comment]
> If I open an empty cpp file, hit <C-n> in insert mode, I get the same error in the screenshot.

Fixed.

**Comment by Shougo** [comment]
> When I hit <C-n> and the popup appears, it doesn't automatically modify the input to its first suggestion (even when the first suggestion is highlighted). And when I hit <C-n> again, it modifies the input to the second suggestion. Which basically means I have to <C-p> back to get the first suggestion inserted.

It is `noinsert` behavior you have set in `completeopt`.
You should know what you have set.

```vim
set completeopt=menu,menuone
```

Fixes your problem.

**Comment by lriuui0x0** [comment]
> You need to restart the editor. No magic.
I restart neovim repeatedly.

That's good to know. Thanks!

> It is noinsert behavior you have set in completeopt.

That does fix my problem. Thanks!

> If I open an empty cpp file, hit in insert mode, I get the same error in the screenshot.
Fixed.

That indeed fixed the error. However, I found that when you're in the top-level scope (in a cpp file) with zero characters inserted for the word, the popup doesn't get shown if you trigger the completion. You have to have at least one character to trigger it successfully. This isn't the case when you're not at top level, i.e. you can see a list of suggestions even when you have zero characters inserted.

I'm using
```
call deoplete#custom#option('auto_complete_popup', 'manual')
call deoplete#custom#option('min_pattern_length', 0)
```

This is not a big problem, just to report so you know :)

**Comment by Shougo** [comment]
OK.  I will fix the problem later.

**Comment by Shougo** [comment]
Fixed it in the latest version.

**Comment by lriuui0x0** [comment]
@Shougo Thanks for the update. Unfortunately I still have the same problem after update. Open an empty cpp file. Press `i` into insert mode. Then presss `<C-n>`, nothing happens. The popup is only shown after I typed at least a character.

**Comment by Shougo** [comment]
It works for me.

**Comment by Shougo** [comment]
> Press i into insert mode. Then presss <C-n>, nothing happens. The popup is only shown after I typed at least a character.

Reproduced the problem.  I will research it.

But it is repoduce-able with your configuration.

https://github.com/Shougo/deoplete.nvim/issues/1079#issuecomment-596272237

It does not work for 0 length string.

**Comment by Shougo** [comment]
I have fixed the problem.

**Comment by lriuui0x0** [comment]
@Shougo Thanks. I can confirm it's fixed :)

**Comment by lriuui0x0** [comment]
@Shougo Sorry to reopen this. I think there's some problem with trying to trigger completion popup manually when the `noinsert` completeopt is set.

I would expect that if  `noinsert` is set, when you trigger popup manually, it should show the popup but with **no suggestion being selected**. But currently, it will have the first suggestion selected, without inserting the first suggestion, making <C-n> skip the first suggestion and go to the second suggestion directly.

A separate issue is that the auto-refreshing behaviour (which probably only makes sense when `noinsert` is set) doesn't work when you try to delete characters - it just closes the popup.

**Comment by Shougo** [comment]
> I would expect that if noinsert is set, when you trigger popup manually, it should show the popup but with no suggestion being selected. But currently, it will have the first suggestion selected, without inserting the first suggestion, making skip the first suggestion and go to the second suggestion directly.

It is the noinsert feature.  You should know what is noinsert.
If you need to select the first suggestion, you need to remove both noinsert and noselect from completeopt.

> A separate issue is that the auto-refreshing behaviour (which probably only makes sense when noinsert is set) doesn't work when you try to delete characters - it just closes the popup.

Sorry.  Unfortunately it is feature.
To refresh when delete characters is auto completion related feature.
deoplete is not created for manual completion.

**Comment by Shougo** [comment]
```vim
set completeopt+=noselect
inoremap <expr> <C-h> pumvisible() ? "\<C-h>" . deoplete#complete() : "\<C-h>"
```

If you really need to auto refresh when `<C-h>`, it works for me.
