### ISSUE TITLE
deoplete auto open popup menu when jump out of pairs and move cursor

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/deoplete.nvim#114]
there are three issues about this plugin,but with my pool english,I only can describe the first one.
### auto open popup menu when jump out of pairs;
installed plugin deoplete, neosnippet.vim with default setting;
```
snippet (
     (${1})${0}
```
```
snippet str
     String${0}
```
then type `(` -> tab -> str -> tab ->tab

then i will get 
  `(String)_ `            _is cursor
but if there are tags named StringBuild or anything else begin with String will be matched ,and shown in the popup menu ,I think it should not be shown ,because the is a `)` after `String`

![Uploading IMG_20160107_201322.jpg…](https://pbs.twimg.com/media/CYHeR4UWAAAkF-v.jpg)

### ctrl + y can not close popup menu
only install deoplete plugin ;
```
vim test.js
```
then type into `windows.` then the popup menu will be shown ,and do not delect any item

then ctrl + y or Enter can not close the popup menu,only Ctrl + e can do it

**Comment by Shougo** [comment]
Fixed.

**Comment by wsdjeg** [comment]
it is amazing,Thanks a lot

**Comment by wsdjeg** [comment]
@Shougo the first issue still appears,even if I have jumped out of pairs, the matched tags also shown

**Comment by Shougo** [comment]
@wsdjeg Please create minimal init.vim.  I have not ESP skills.
And please upload the tags file.

**Comment by wsdjeg** [comment]
@Shougo I hava finished test ,and here is my Test branch
https://github.com/wsdjeg/DotFiles/blob/neosnippet-test/vimrc   17lines
tags   
```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME	Exuberant Ctags	//
!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	/official site/
!_TAG_PROGRAM_VERSION	5.9~svn20110310	//
String	test/String.java	/^public class String {$/;"	c
StringTest	test/StringTest.java	/^public class StringTest {$/;"	c
```
snippets
```
snippet     (
options     word
    (${1:#:output})${2}
```
```
snippet     str
abbr        str
options     word
    String${1}
```

Then open a file 
type into `(` -> type tab -> type `str` -> type tab -> type tab

**Comment by Shougo** [comment]
Fixed.
Please update deoplete and neosnippet.
