### ISSUE TITLE
Haskell completion everywhere… except in `.hs` files

### ISSUE THREAD

**Issue by raichoo** [Shougo/deoplete.nvim#124]
Hi,
I'm having a very odd behavior here. `deoplete` + `neco-ghc` seem to do Haskell completion in every filetype except in `.hs` files. I've tested it an `.c` and `.rb` files, even though it is not supposed to start up there it merrily does its thing ^^.
I have no idea what additional information I can give here. I've removed `haskell-vim` to check if it's somewhat related to this issue, but it did not change anything.

Kind regards,
raichoo

**Comment by Shougo** [comment]
Fixed.  Please update deoplete.

**Comment by raichoo** [comment]
Ok, that fixes the issue with completion for other filetypes. Completion in `.hs` files is still not present.
`:NecoGhcDiagnostics` looks happy though.

    Current filetype: haskell                                                                                                                     
    ghc-mod is executable: 1                                                                                                                      
    omnifunc:                                                                                                                                     
    neocomplete.vim: 0                                                                                                                            
    neocomplcache.vim: 0                                                                                                                          
    YouCompleteMe: 0                                                                                                                              
    vimproc.vim: 902                                                                                                                              
    ghc-mod: 5.4.0.0                                                                                                                              
    Imported modules: Prelude                                                                                                                     
    Number of symbols in Prelude: 252

**Comment by raichoo** [comment]
Correction. I've checked completion with language extensions. This does not seem to work. Everything else works fine though. Should I report this to `neco-ghc`?

**Comment by Shougo** [comment]
You should create issue in neco-ghc.
I will try it.
But please create minimal init.vim.
I cannot reproduce it.
