### ISSUE TITLE
completion not showing up when vim-jsx is enabled. 

### ISSUE THREAD

**Issue by aakashsigdel** [Shougo/deoplete.nvim#134]
Deoplete completion doesn't show up for javascript when vim-jsx is enabled

here is the minimum .vimrc to reproduce the problem.

> call plug#begin('~/.vim/plugged')
> Plug 'mxw/vim-jsx'
> call plug#end()

> let g:jsx_ext_required = 0

Vim plug is used for installing vim-jsx

Here are the gifs of the problem in action:

![exportdeonvim](https://cloud.githubusercontent.com/assets/4772643/12401348/eac86990-be4d-11e5-8932-d5e649844108.gif)

**Comment by Shougo** [comment]
Fixed.

**Comment by LS8** [comment]
Still not working for me, minimal .vimrc to reproduce is the same as @aakashsigdel provided.
[mxw/vim-jsx](https://github.com/mxw/vim-jsx) in conjunction with `let g:jsx_ext_required = 0` breaks the js completion that should be provided by deoplete.
Also related to #44 and [mxw/vim-js#68](https://github.com/mxw/vim-jsx/issues/68).

**Comment by Shougo** [comment]
Fixed.  And it is needed.

```vim
let g:deoplete#omni#input_patterns = {}
let g:deoplete#omni#input_patterns.javascript = '[^. *\t]\.\w*'
```

**Comment by jdivock** [comment]
I'm still seeing this behavior even with the config options your provided

https://github.com/jdivock/dotfiles/blob/master/nvim/init.vim

**Comment by Shougo** [comment]
@jdivock I cannot reproduce the problem.
Please use the latest deoplete.nvim.

```vim
set rtp+=~/.cache/dein/repos/github.com/Shougo/deoplete.nvim/
set rtp+=~/src/vim-jsx/

let g:deoplete#enable_at_startup = 1
let g:jsx_ext_required = 0

let g:deoplete#omni#input_patterns = {}
let g:deoplete#omni#input_patterns.javascript = '[^. *\t]\.\w*'
```

**Comment by Shougo** [comment]
@jdivock Why don't you test the minimal init.vim?

**Comment by Shougo** [comment]
https://github.com/jdivock/dotfiles/blob/master/nvim/init.vim

It has not deoplete configuration.
Hm...
