### ISSUE TITLE
unable to auto pop out css styling suggestion in <style> tag in html file

### ISSUE THREAD

**Issue by wangsongiam** [Shougo/deoplete.nvim#424]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
I just migrated to Deoplete, and it worked perfectly in css/javascript files(thanks for your great work). Yet when writing some css styles in `<style>` tag inside a HTML file, nothing automatically pop out unless hitting `<c-x><c-o>` the old way(same thing goes with javascript inside of `<script>`tag).

## Expected
Automatically pop out the suggestions when writing css, javascript in `<style>`,`<script>` tags inside of HTML files.

## Environment Information

 * deoplete version(SHA1): latest

 * OS: 10.12.2

 * neovim version: 

 * `:CheckHealth` result(neovim ver.0.1.5-452+):
```
health#deoplete#check ======================================================================== ## deoplete.nvim - SUCCESS: has("nvim") was successful SUCCESS: has("python3") was successful INFO: If you're still having problems, try the following commands: $ export NVIM_PYTHON_LOG_FILE=/tmp/log $ export NVIM_PYTHON_LOG_LEVEL=DEBUG $ nvim $ cat /tmp/log_{PID} and then create an issue on github health#jedi#check ======================================================================== ## jedi jedi-vim: the detected Python version (bash: no job control in this shell^@2) is not functional. Is the "neovim" module installed? While jedi-vim will work, it might not use the expected Python path.  #### Jedi-vim debug information
Using Python version: 2
 - sys.version: 2.7.10 (default, Jul 30 2016, 19:40:32), [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
 - site module: /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.pyc
Jedi path: /Users/wangsong/dotfiles/nvim/bundle/jedi-vim/jedi/jedi/__init__.pyc
 - version: 0.10.0
 - sys_path:
    - /Users/wangsong/dotfiles/nvim/bundle/jedi-vim
    - /Library/Python/2.7/site-packages/virtualenv-15.1.0-py2.7.egg
    - /Library/Python/2.7/site-packages/pyproj-1.9.5.1-py2.7-macosx-10.12-intel.egg
    - /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
    - /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
    - /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
    - /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
    - /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
    - /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
    - /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
    - /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
    - /Users/wangsong/Library/Python/2.7/lib/python/site-packages
    - /Library/Python/2.7/site-packages
    - /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
    - /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC
    - _vim_path_
    - /Users/wangsong/dotfiles/.vim/bundle/vim-virtualenv/autoload
    - /Users/wangsong/dotfiles/nvim/bundle/MatchTagAlways/autoload/../python
jedi-vim git version: bash: no job control in this shell
0.8.0-65-geba90e6
jedi git submodule status: bash: no job control in this shell
 f05c0714c701ab784bd344aa063acd216fb45ec0 jedi (v0.9.0-550-gf05c071)


##### Settings

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminfo
  - ERROR: key_backspace (kbs) entry is ^H (ASCII DELETE): key_backspace=^H,
    - SUGGESTIONS:
      - Set key_backspace to \177 (ASCII BACKSPACE). Run these commands:
          infocmp $TERM | sed 's/kbs=^[hH]/kbs=\\177/' > $TERM.ti
          tic $TERM.ti
      - See https://github.com/neovim/neovim/wiki/FAQ

## tmux
  - SUCCESS: escape-time: bash:nojobcontrolinthisshell[warn]kq_init:detectedbrokenkqueue;notusing.:Undefinederror:00ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2.7 in the environment.
  - SUCCESS: pyenv found: "/usr/local/Cellar/pyenv/1.0.7/libexec/pyenv"
  - WARNING: pyenv is not set up optimally.
    - SUGGESTIONS:
      - Suggestion: Create a virtualenv specifically for Neovim using pyenv and use "g:python_host_prog".  This will avoid the need to install Neovim's Python client in each version/virtualenv.
  - ERROR: "bash: no job control in this shell/usr/bin/python2.7" was not found.
  - INFO: Executable: Not found

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - SUCCESS: pyenv found: "/usr/local/Cellar/pyenv/1.0.7/libexec/pyenv"
  - WARNING: pyenv is not set up optimally.
    - SUGGESTIONS:
      - Suggestion: Create a virtualenv specifically for Neovim using pyenv and use "g:python3_host_prog".  This will avoid the need to install Neovim's Python client in each version/virtualenv.
  - ERROR: "bash: no job control in this shell/usr/local/bin/python3" was not found.
  - INFO: Executable: Not found

## Ruby provider
  - SUCCESS: Found up-to-date neovim RubyGem
  - INFO: Ruby Version: bash: no job control in this shellruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
  - INFO: Host Executable: /usr/local/bin/neovim-ruby-host
  - INFO: Host Version: bash: no job control in this shell0.3.1

```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" vim-plug
call plug#begin('~/.local/share/nvim/plugged')

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

call plug#end()

" omnifunc
aug omnicomplete
  au!
  au FileType css,sass,scss,stylus,less setl omnifunc=csscomplete#CompleteCSS
  au FileType html,htmldjango,jinja,markdown setl omnifunc=emmet#completeTag
  au FileType javascript,jsx,javascript.jsx setl omnifunc=tern#Complete
  au FileType python setl omnifunc=pythoncomplete#Complete
  au FileType xml setl omnifunc=xmlcomplete#CompleteTags
aug END

au FileType html setl omnifunc=csscomplete#CompleteCSS

" deoplete
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_smart_case = 1
let g:deoplete#auto_refresh_delay = 0
let g:deoplete#auto_complete_delay = 0

```

## The reproduce ways from neovim starting (Required!)

 1. `:e test.html`
 2. input this
<img width="196" alt="screen shot 2017-01-29 at 6 13 19 pm" src="https://cloud.githubusercontent.com/assets/19645990/22409158/94397c70-e653-11e6-96e2-cbb43262f380.png">

 3. `<c-x><c-o>` and suggestion will pop out

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by tweekmonster** [comment]
Try installing this: https://github.com/Shougo/context_filetype.vim

@Shougo I think `context_filetype.vim` should be bundled with Deoplete.  The script is "simple" enough to copy into `autoload` and update periodically when needed.  WDYT?

**Comment by wangsongiam** [comment]
@tweekmonster Thanks for the reply, I've tried this one but it didn't work out, so I post another  [issue there](https://github.com/Shougo/context_filetype.vim/issues/27)

**Comment by Shougo** [comment]
Fixed.  Please install context_filetype.vim.

> @Shougo I think context_filetype.vim should be bundled with Deoplete. The script is "simple" enough to copy into autoload and update periodically when needed. WDYT?

I don't think so.
The plugin is configurable and used for other plugins.

**Comment by wangsongiam** [comment]
I've tried to reinstall Deoplete and context_filetype.vim, yet still no luck in coding CSS in `<style>` tag :(

**Comment by wangsongiam** [comment]
@Shougo Just found out that Deoplete is not showing omnifunction inside HTML file at all. I can see all those suggestions if I hit `<c-x><c-o>`, no matter it's inside a tag or not(and works fine with context_filetype.vim), but it just doesn't work automatically. And It's just for html files, other file types are all fine.
![2017-01-31 07 16 33](https://cloud.githubusercontent.com/assets/19645990/22464533/52a225e0-e785-11e6-93bb-43afba6ac29e.gif)

**Comment by Shougo** [comment]
> I've tried to reinstall/update Deoplete and context_filetype.vim, yet still no luck with coding CSS in `<style>` tag :(

I cannot reproduce the CSS problem.
The plugins are latest and loaded properly?

I have fixed the javascript problem.
Please update deoplete.
