### ISSUE TITLE
Popup doesn't show up automatically when typing

### ISSUE THREAD

**Issue by ahmedelgabri** [Shougo/deoplete.nvim#44]
I'm trying to recreate my current Vim setup in Neovim

In vim I'm using Neocomplete with these settings

```vim
    let g:neocomplete#enable_at_startup = 1
    let g:neocomplete#enable_smart_case = 1
    let g:neocomplete#sources#syntax#min_keyword_length = 3
    let g:neocomplete#auto_completion_start_length = 1
    let g:neocomplete#sources#buffer#cache_limit_size = 50000
    let g:neocomplete#data_directory = $HOME.'/.vim/cache/noecompl'
    let g:neocomplete#sources#syntax#min_keyword_length = 3
    let g:neocomplete#force_omni_input_patterns = get(g:, 'neocomplete#force_omni_input_patterns', {})
    let g:neocomplete#force_omni_input_patterns.javascript = '[^. \t]\.\w*'
    " Tab completion.
    inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
```

and in Neovim I have this right now

```vim
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#auto_completion_start_length = 1
    let g:deoplete#enable_smart_case = 1
    let g:deoplete#enable_auto_close_preview = 1
    let g:deoplete#data_directory = $HOME.'.vim/cache/deoplete'
    let g:deoplete#force_omni_input_patterns = get(g:, 'deoplete#force_omni_input_patterns', {})
    let g:deoplete#force_omni_input_patterns.javascript = '[^. \t]\.\w*'
    inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
```

1. The autocomplete popup doesn't show automatically while typing in deoplete unlike neocomplete.
2. How can use `TAB` to match the behaviour of neocomplete?

**Comment by Shougo** [comment]
`g:deoplete#enable_auto_close_preview` and `g:deoplete#data_directory` are not exists.
`g:deoplete#omni_input_patterns` is correct name.  Please read the documentation.

You should read CONTRIBUTING.md.  And please create minimal.vimrc.

It is in FAQ trouble shooting.

```
Q: deoplete does not work...

A: Please check followings.

  1. Please update neovim to latest version.

  2. Please update neovim python3 module to latest version.
>
	$ sudo pip3 install neovim --upgrade
<
  3. Please execute |:UpdateRemotePlugins| command manually.
```

deoplete plugin is already loaded?
python3 interface is enabled?

**Comment by ahmedelgabri** [comment]
I have the latest nvim and nvim python3 package.

minimal.vimrc

```vim

    set runtimepath+=~/.vim/plugged/deoplete.nvim/

    let g:deoplete#enable_at_startup = 1
    let g:deoplete#auto_completion_start_length = 1
    let g:deoplete#enable_smart_case = 1
    let g:deoplete#deoplete_onmni_patterns = get(g:, 'deoplete#force_omni_input_patterns', {})
    let g:deoplete#deoplete_onmni_patterns.javascript = '[^. \t]\.\w*'
    inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
```

log file

```
2015-09-17 22:18:00,175 [DEBUG @ msgpack_stream.py:send:36] 5263 - sent [0, 1, b'vim_get_api_info', ()]
2015-09-17 22:18:00,175 [DEBUG @ base.py:send:113] 5263 - Sending 'b'\x94\x00\x01\xc4\x10vim_get_api_info\x90''
2015-09-17 22:18:00,176 [DEBUG @ base.py:run:138] 5263 - Entering event loop
2015-09-17 22:18:00,176 [DEBUG @ msgpack_stream.py:_on_data:57] 5263 - waiting for message...
2015-09-17 22:18:00,176 [DEBUG @ msgpack_stream.py:_on_data:59] 5263 - received message: [0, 1, b'poll', []]
2015-09-17 22:18:00,176 [DEBUG @ async_session.py:_on_request:86] 5263 - received request: b'poll', []
2015-09-17 22:18:00,176 [DEBUG @ msgpack_stream.py:_on_data:57] 5263 - waiting for message...
2015-09-17 22:18:00,176 [DEBUG @ msgpack_stream.py:_on_data:62] 5263 - unpacker needs more data...
2015-09-17 22:18:00,176 [DEBUG @ msgpack_stream.py:_on_data:57] 5263 - waiting for message...
2015-09-17 22:18:00,176 [DEBUG @ msgpack_stream.py:_on_data:59] 5263 - received message: [1, 1, None, [1, {b'functions': [{b'name': b'buffer_line_count', b'can_fail': True, b'async': False, b'return_type': b'Integer', b'parameters': [[b'Buffer', b'buffer']]}, {b'name': b'buffer_get_line', b'can_fail': True, b'async': False, b'return_type': b'String', b'parameters': [[b'Buffer', b'buffer'], [b'Integer', b'index']]}, {b'name': b'buffer_set_line', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Buffer', b'buffer'], [b'Integer', b'index'], [b'String', b'line']]}, {b'name': b'buffer_del_line', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Buffer', b'buffer'], [b'Integer', b'index']]}, {b'name': b'buffer_get_line_slice', b'can_fail': True, b'async': False, b'return_type': b'ArrayOf(String)', b'parameters': [[b'Buffer', b'buffer'], [b'Integer', b'start'], [b'Integer', b'end'], [b'Boolean', b'include_start'], [b'Boolean', b'include_end']]}, {b'name': b'buffer_set_line_slice', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Buffer', b'buffer'], [b'Integer', b'start'], [b'Integer', b'end'], [b'Boolean', b'include_start'], [b'Boolean', b'include_end'], [b'ArrayOf(String)', b'replacement']]}, {b'name': b'buffer_get_var', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'Buffer', b'buffer'], [b'String', b'name']]}, {b'name': b'buffer_set_var', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'Buffer', b'buffer'], [b'String', b'name'], [b'Object', b'value']]}, {b'name': b'buffer_get_option', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'Buffer', b'buffer'], [b'String', b'name']]}, {b'name': b'buffer_set_option', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Buffer', b'buffer'], [b'String', b'name'], [b'Object', b'value']]}, {b'name': b'buffer_get_number', b'can_fail': True, b'async': False, b'return_type': b'Integer', b'parameters': [[b'Buffer', b'buffer']]}, {b'name': b'buffer_get_name', b'can_fail': True, b'async': False, b'return_type': b'String', b'parameters': [[b'Buffer', b'buffer']]}, {b'name': b'buffer_set_name', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Buffer', b'buffer'], [b'String', b'name']]}, {b'name': b'buffer_is_valid', b'async': False, b'return_type': b'Boolean', b'parameters': [[b'Buffer', b'buffer']]}, {b'name': b'buffer_insert', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Buffer', b'buffer'], [b'Integer', b'lnum'], [b'ArrayOf(String)', b'lines']]}, {b'name': b'buffer_get_mark', b'can_fail': True, b'async': False, b'return_type': b'ArrayOf(Integer, 2)', b'parameters': [[b'Buffer', b'buffer'], [b'String', b'name']]}, {b'name': b'tabpage_get_windows', b'can_fail': True, b'async': False, b'return_type': b'ArrayOf(Window)', b'parameters': [[b'Tabpage', b'tabpage']]}, {b'name': b'tabpage_get_var', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'Tabpage', b'tabpage'], [b'String', b'name']]}, {b'name': b'tabpage_set_var', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'Tabpage', b'tabpage'], [b'String', b'name'], [b'Object', b'value']]}, {b'name': b'tabpage_get_window', b'can_fail': True, b'async': False, b'return_type': b'Window', b'parameters': [[b'Tabpage', b'tabpage']]}, {b'name': b'tabpage_is_valid', b'async': False, b'return_type': b'Boolean', b'parameters': [[b'Tabpage', b'tabpage']]}, {b'name': b'vim_command', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'String', b'str']]}, {b'name': b'vim_feedkeys', b'async': False, b'return_type': b'void', b'parameters': [[b'String', b'keys'], [b'String', b'mode'], [b'Boolean', b'escape_csi']]}, {b'name': b'vim_input', b'async': True, b'return_type': b'Integer', b'parameters': [[b'String', b'keys']]}, {b'name': b'vim_replace_termcodes', b'async': False, b'return_type': b'String', b'parameters': [[b'String', b'str'], [b'Boolean', b'from_part'], [b'Boolean', b'do_lt'], [b'Boolean', b'special']]}, {b'name': b'vim_command_output', b'can_fail': True, b'async': False, b'return_type': b'String', b'parameters': [[b'String', b'str']]}, {b'name': b'vim_eval', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'String', b'str']]}, {b'name': b'vim_call_function', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'String', b'fname'], [b'Array', b'args']]}, {b'name': b'vim_strwidth', b'can_fail': True, b'async': False, b'return_type': b'Integer', b'parameters': [[b'String', b'str']]}, {b'name': b'vim_list_runtime_paths', b'async': False, b'return_type': b'ArrayOf(String)', b'parameters': []}, {b'name': b'vim_change_directory', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'String', b'dir']]}, {b'name': b'vim_get_current_line', b'can_fail': True, b'async': False, b'return_type': b'String', b'parameters': []}, {b'name': b'vim_set_current_line', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'String', b'line']]}, {b'name': b'vim_del_current_line', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': []}, {b'name': b'vim_get_var', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'String', b'name']]}, {b'name': b'vim_set_var', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'String', b'name'], [b'Object', b'value']]}, {b'name': b'vim_get_vvar', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'String', b'name']]}, {b'name': b'vim_get_option', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'String', b'name']]}, {b'name': b'vim_set_option', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'String', b'name'], [b'Object', b'value']]}, {b'name': b'vim_out_write', b'async': False, b'return_type': b'void', b'parameters': [[b'String', b'str']]}, {b'name': b'vim_err_write', b'async': False, b'return_type': b'void', b'parameters': [[b'String', b'str']]}, {b'name': b'vim_report_error', b'async': False, b'return_type': b'void', b'parameters': [[b'String', b'str']]}, {b'name': b'vim_get_buffers', b'async': False, b'return_type': b'ArrayOf(Buffer)', b'parameters': []}, {b'name': b'vim_get_current_buffer', b'async': False, b'return_type': b'Buffer', b'parameters': []}, {b'name': b'vim_set_current_buffer', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Buffer', b'buffer']]}, {b'name': b'vim_get_windows', b'async': False, b'return_type': b'ArrayOf(Window)', b'parameters': []}, {b'name': b'vim_get_current_window', b'async': False, b'return_type': b'Window', b'parameters': []}, {b'name': b'vim_set_current_window', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Window', b'window']]}, {b'name': b'vim_get_tabpages', b'async': False, b'return_type': b'ArrayOf(Tabpage)', b'parameters': []}, {b'name': b'vim_get_current_tabpage', b'async': False, b'return_type': b'Tabpage', b'parameters': []}, {b'name': b'vim_set_current_tabpage', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Tabpage', b'tabpage']]}, {b'receives_channel_id': True, b'name': b'vim_subscribe', b'async': False, b'return_type': b'void', b'parameters': [[b'String', b'event']]}, {b'receives_channel_id': True, b'name': b'vim_unsubscribe', b'async': False, b'return_type': b'void', b'parameters': [[b'String', b'event']]}, {b'name': b'vim_name_to_color', b'async': False, b'return_type': b'Integer', b'parameters': [[b'String', b'name']]}, {b'name': b'vim_get_color_map', b'async': False, b'return_type': b'Dictionary', b'parameters': []}, {b'receives_channel_id': True, b'name': b'vim_get_api_info', b'async': True, b'return_type': b'Array', b'parameters': []}, {b'name': b'window_get_buffer', b'can_fail': True, b'async': False, b'return_type': b'Buffer', b'parameters': [[b'Window', b'window']]}, {b'name': b'window_get_cursor', b'can_fail': True, b'async': False, b'return_type': b'ArrayOf(Integer, 2)', b'parameters': [[b'Window', b'window']]}, {b'name': b'window_set_cursor', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Window', b'window'], [b'ArrayOf(Integer, 2)', b'pos']]}, {b'name': b'window_get_height', b'can_fail': True, b'async': False, b'return_type': b'Integer', b'parameters': [[b'Window', b'window']]}, {b'name': b'window_set_height', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Window', b'window'], [b'Integer', b'height']]}, {b'name': b'window_get_width', b'can_fail': True, b'async': False, b'return_type': b'Integer', b'parameters': [[b'Window', b'window']]}, {b'name': b'window_set_width', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Window', b'window'], [b'Integer', b'width']]}, {b'name': b'window_get_var', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'Window', b'window'], [b'String', b'name']]}, {b'name': b'window_set_var', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'Window', b'window'], [b'String', b'name'], [b'Object', b'value']]}, {b'name': b'window_get_option', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'Window', b'window'], [b'String', b'name']]}, {b'name': b'window_set_option', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Window', b'window'], [b'String', b'name'], [b'Object', b'value']]}, {b'name': b'window_get_position', b'can_fail': True, b'async': False, b'return_type': b'ArrayOf(Integer, 2)', b'parameters': [[b'Window', b'window']]}, {b'name': b'window_get_tabpage', b'can_fail': True, b'async': False, b'return_type': b'Tabpage', b'parameters': [[b'Window', b'window']]}, {b'name': b'window_is_valid', b'async': False, b'return_type': b'Boolean', b'parameters': [[b'Window', b'window']]}], b'types': {b'Buffer': {b'id': 0}, b'Window': {b'id': 1}, b'Tabpage': {b'id': 2}}, b'error_types': {b'Validation': {b'id': 1}, b'Exception': {b'id': 0}}}]]
2015-09-17 22:18:00,177 [DEBUG @ async_session.py:_on_response:95] 5263 - received response: None, [1, {b'functions': [{b'name': b'buffer_line_count', b'can_fail': True, b'async': False, b'return_type': b'Integer', b'parameters': [[b'Buffer', b'buffer']]}, {b'name': b'buffer_get_line', b'can_fail': True, b'async': False, b'return_type': b'String', b'parameters': [[b'Buffer', b'buffer'], [b'Integer', b'index']]}, {b'name': b'buffer_set_line', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Buffer', b'buffer'], [b'Integer', b'index'], [b'String', b'line']]}, {b'name': b'buffer_del_line', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Buffer', b'buffer'], [b'Integer', b'index']]}, {b'name': b'buffer_get_line_slice', b'can_fail': True, b'async': False, b'return_type': b'ArrayOf(String)', b'parameters': [[b'Buffer', b'buffer'], [b'Integer', b'start'], [b'Integer', b'end'], [b'Boolean', b'include_start'], [b'Boolean', b'include_end']]}, {b'name': b'buffer_set_line_slice', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Buffer', b'buffer'], [b'Integer', b'start'], [b'Integer', b'end'], [b'Boolean', b'include_start'], [b'Boolean', b'include_end'], [b'ArrayOf(String)', b'replacement']]}, {b'name': b'buffer_get_var', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'Buffer', b'buffer'], [b'String', b'name']]}, {b'name': b'buffer_set_var', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'Buffer', b'buffer'], [b'String', b'name'], [b'Object', b'value']]}, {b'name': b'buffer_get_option', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'Buffer', b'buffer'], [b'String', b'name']]}, {b'name': b'buffer_set_option', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Buffer', b'buffer'], [b'String', b'name'], [b'Object', b'value']]}, {b'name': b'buffer_get_number', b'can_fail': True, b'async': False, b'return_type': b'Integer', b'parameters': [[b'Buffer', b'buffer']]}, {b'name': b'buffer_get_name', b'can_fail': True, b'async': False, b'return_type': b'String', b'parameters': [[b'Buffer', b'buffer']]}, {b'name': b'buffer_set_name', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Buffer', b'buffer'], [b'String', b'name']]}, {b'name': b'buffer_is_valid', b'async': False, b'return_type': b'Boolean', b'parameters': [[b'Buffer', b'buffer']]}, {b'name': b'buffer_insert', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Buffer', b'buffer'], [b'Integer', b'lnum'], [b'ArrayOf(String)', b'lines']]}, {b'name': b'buffer_get_mark', b'can_fail': True, b'async': False, b'return_type': b'ArrayOf(Integer, 2)', b'parameters': [[b'Buffer', b'buffer'], [b'String', b'name']]}, {b'name': b'tabpage_get_windows', b'can_fail': True, b'async': False, b'return_type': b'ArrayOf(Window)', b'parameters': [[b'Tabpage', b'tabpage']]}, {b'name': b'tabpage_get_var', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'Tabpage', b'tabpage'], [b'String', b'name']]}, {b'name': b'tabpage_set_var', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'Tabpage', b'tabpage'], [b'String', b'name'], [b'Object', b'value']]}, {b'name': b'tabpage_get_window', b'can_fail': True, b'async': False, b'return_type': b'Window', b'parameters': [[b'Tabpage', b'tabpage']]}, {b'name': b'tabpage_is_valid', b'async': False, b'return_type': b'Boolean', b'parameters': [[b'Tabpage', b'tabpage']]}, {b'name': b'vim_command', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'String', b'str']]}, {b'name': b'vim_feedkeys', b'async': False, b'return_type': b'void', b'parameters': [[b'String', b'keys'], [b'String', b'mode'], [b'Boolean', b'escape_csi']]}, {b'name': b'vim_input', b'async': True, b'return_type': b'Integer', b'parameters': [[b'String', b'keys']]}, {b'name': b'vim_replace_termcodes', b'async': False, b'return_type': b'String', b'parameters': [[b'String', b'str'], [b'Boolean', b'from_part'], [b'Boolean', b'do_lt'], [b'Boolean', b'special']]}, {b'name': b'vim_command_output', b'can_fail': True, b'async': False, b'return_type': b'String', b'parameters': [[b'String', b'str']]}, {b'name': b'vim_eval', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'String', b'str']]}, {b'name': b'vim_call_function', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'String', b'fname'], [b'Array', b'args']]}, {b'name': b'vim_strwidth', b'can_fail': True, b'async': False, b'return_type': b'Integer', b'parameters': [[b'String', b'str']]}, {b'name': b'vim_list_runtime_paths', b'async': False, b'return_type': b'ArrayOf(String)', b'parameters': []}, {b'name': b'vim_change_directory', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'String', b'dir']]}, {b'name': b'vim_get_current_line', b'can_fail': True, b'async': False, b'return_type': b'String', b'parameters': []}, {b'name': b'vim_set_current_line', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'String', b'line']]}, {b'name': b'vim_del_current_line', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': []}, {b'name': b'vim_get_var', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'String', b'name']]}, {b'name': b'vim_set_var', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'String', b'name'], [b'Object', b'value']]}, {b'name': b'vim_get_vvar', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'String', b'name']]}, {b'name': b'vim_get_option', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'String', b'name']]}, {b'name': b'vim_set_option', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'String', b'name'], [b'Object', b'value']]}, {b'name': b'vim_out_write', b'async': False, b'return_type': b'void', b'parameters': [[b'String', b'str']]}, {b'name': b'vim_err_write', b'async': False, b'return_type': b'void', b'parameters': [[b'String', b'str']]}, {b'name': b'vim_report_error', b'async': False, b'return_type': b'void', b'parameters': [[b'String', b'str']]}, {b'name': b'vim_get_buffers', b'async': False, b'return_type': b'ArrayOf(Buffer)', b'parameters': []}, {b'name': b'vim_get_current_buffer', b'async': False, b'return_type': b'Buffer', b'parameters': []}, {b'name': b'vim_set_current_buffer', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Buffer', b'buffer']]}, {b'name': b'vim_get_windows', b'async': False, b'return_type': b'ArrayOf(Window)', b'parameters': []}, {b'name': b'vim_get_current_window', b'async': False, b'return_type': b'Window', b'parameters': []}, {b'name': b'vim_set_current_window', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Window', b'window']]}, {b'name': b'vim_get_tabpages', b'async': False, b'return_type': b'ArrayOf(Tabpage)', b'parameters': []}, {b'name': b'vim_get_current_tabpage', b'async': False, b'return_type': b'Tabpage', b'parameters': []}, {b'name': b'vim_set_current_tabpage', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Tabpage', b'tabpage']]}, {b'receives_channel_id': True, b'name': b'vim_subscribe', b'async': False, b'return_type': b'void', b'parameters': [[b'String', b'event']]}, {b'receives_channel_id': True, b'name': b'vim_unsubscribe', b'async': False, b'return_type': b'void', b'parameters': [[b'String', b'event']]}, {b'name': b'vim_name_to_color', b'async': False, b'return_type': b'Integer', b'parameters': [[b'String', b'name']]}, {b'name': b'vim_get_color_map', b'async': False, b'return_type': b'Dictionary', b'parameters': []}, {b'receives_channel_id': True, b'name': b'vim_get_api_info', b'async': True, b'return_type': b'Array', b'parameters': []}, {b'name': b'window_get_buffer', b'can_fail': True, b'async': False, b'return_type': b'Buffer', b'parameters': [[b'Window', b'window']]}, {b'name': b'window_get_cursor', b'can_fail': True, b'async': False, b'return_type': b'ArrayOf(Integer, 2)', b'parameters': [[b'Window', b'window']]}, {b'name': b'window_set_cursor', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Window', b'window'], [b'ArrayOf(Integer, 2)', b'pos']]}, {b'name': b'window_get_height', b'can_fail': True, b'async': False, b'return_type': b'Integer', b'parameters': [[b'Window', b'window']]}, {b'name': b'window_set_height', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Window', b'window'], [b'Integer', b'height']]}, {b'name': b'window_get_width', b'can_fail': True, b'async': False, b'return_type': b'Integer', b'parameters': [[b'Window', b'window']]}, {b'name': b'window_set_width', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Window', b'window'], [b'Integer', b'width']]}, {b'name': b'window_get_var', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'Window', b'window'], [b'String', b'name']]}, {b'name': b'window_set_var', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'Window', b'window'], [b'String', b'name'], [b'Object', b'value']]}, {b'name': b'window_get_option', b'can_fail': True, b'async': False, b'return_type': b'Object', b'parameters': [[b'Window', b'window'], [b'String', b'name']]}, {b'name': b'window_set_option', b'can_fail': True, b'async': False, b'return_type': b'void', b'parameters': [[b'Window', b'window'], [b'String', b'name'], [b'Object', b'value']]}, {b'name': b'window_get_position', b'can_fail': True, b'async': False, b'return_type': b'ArrayOf(Integer, 2)', b'parameters': [[b'Window', b'window']]}, {b'name': b'window_get_tabpage', b'can_fail': True, b'async': False, b'return_type': b'Tabpage', b'parameters': [[b'Window', b'window']]}, {b'name': b'window_is_valid', b'async': False, b'return_type': b'Boolean', b'parameters': [[b'Window', b'window']]}], b'types': {b'Buffer': {b'id': 0}, b'Window': {b'id': 1}, b'Tabpage': {b'id': 2}}, b'error_types': {b'Validation': {b'id': 1}, b'Exception': {b'id': 0}}}]
2015-09-17 22:18:00,177 [DEBUG @ base.py:stop:149] 5263 - Stopped event loop
2015-09-17 22:18:00,177 [DEBUG @ msgpack_stream.py:_on_data:57] 5263 - waiting for message...
2015-09-17 22:18:00,177 [DEBUG @ msgpack_stream.py:_on_data:62] 5263 - unpacker needs more data...
2015-09-17 22:18:00,177 [DEBUG @ base.py:run:140] 5263 - Exited event loop
2015-09-17 22:18:00,177 [DEBUG @ msgpack_stream.py:send:36] 5263 - sent [0, 2, b'vim_get_option', (b'encoding',)]
2015-09-17 22:18:00,177 [DEBUG @ base.py:send:113] 5263 - Sending 'b'\x94\x00\x02\xc4\x0evim_get_option\x91\xc4\x08encoding''
2015-09-17 22:18:00,177 [DEBUG @ base.py:run:138] 5263 - Entering event loop
2015-09-17 22:18:00,177 [DEBUG @ msgpack_stream.py:_on_data:57] 5263 - waiting for message...
2015-09-17 22:18:00,178 [DEBUG @ msgpack_stream.py:_on_data:59] 5263 - received message: [1, 2, None, b'utf-8']
2015-09-17 22:18:00,178 [DEBUG @ async_session.py:_on_response:95] 5263 - received response: None, b'utf-8'
2015-09-17 22:18:00,178 [DEBUG @ base.py:stop:149] 5263 - Stopped event loop
2015-09-17 22:18:00,178 [DEBUG @ msgpack_stream.py:_on_data:57] 5263 - waiting for message...
2015-09-17 22:18:00,178 [DEBUG @ msgpack_stream.py:_on_data:62] 5263 - unpacker needs more data...
2015-09-17 22:18:00,178 [DEBUG @ base.py:run:140] 5263 - Exited event loop
2015-09-17 22:18:00,180 [DEBUG @ msgpack_stream.py:send:36] 5263 - sent [0, 3, 'vim_get_option', ('encoding',)]
2015-09-17 22:18:00,180 [DEBUG @ base.py:send:113] 5263 - Sending 'b'\x94\x00\x03\xaevim_get_option\x91\xa8encoding''
2015-09-17 22:18:00,180 [DEBUG @ base.py:run:138] 5263 - Entering event loop
2015-09-17 22:18:00,180 [DEBUG @ msgpack_stream.py:_on_data:57] 5263 - waiting for message...
2015-09-17 22:18:00,180 [DEBUG @ msgpack_stream.py:_on_data:59] 5263 - received message: [1, 3, None, b'utf-8']
2015-09-17 22:18:00,180 [DEBUG @ async_session.py:_on_response:95] 5263 - received response: None, b'utf-8'
2015-09-17 22:18:00,180 [DEBUG @ base.py:stop:149] 5263 - Stopped event loop
2015-09-17 22:18:00,181 [DEBUG @ msgpack_stream.py:_on_data:57] 5263 - waiting for message...
2015-09-17 22:18:00,181 [DEBUG @ msgpack_stream.py:_on_data:62] 5263 - unpacker needs more data...
2015-09-17 22:18:00,181 [DEBUG @ base.py:run:140] 5263 - Exited event loop
2015-09-17 22:18:00,182 [DEBUG @ msgpack_stream.py:send:36] 5263 - sent [0, 4, 'vim_eval', ('tempname()',)]
2015-09-17 22:18:00,182 [DEBUG @ base.py:send:113] 5263 - Sending 'b'\x94\x00\x04\xa8vim_eval\x91\xaatempname()''
2015-09-17 22:18:00,182 [DEBUG @ session.py:_yielding_request:145] 5263 - yielding from greenlet <greenlet.greenlet object at 0x1093bb930> to wait for response
2015-09-17 22:18:00,182 [DEBUG @ session.py:_on_request:189] 5263 - received rpc request, greenlet <greenlet.greenlet object at 0x1093bbd58> will handle it
2015-09-17 22:18:00,182 [DEBUG @ host.py:_on_request:64] 5263 - calling request handler for "poll", args: "[]"
2015-09-17 22:18:00,182 [DEBUG @ host.py:_on_request:66] 5263 - request handler for 'poll []' returns: ok
2015-09-17 22:18:00,182 [DEBUG @ session.py:handler:179] 5263 - greenlet <greenlet.greenlet object at 0x1093bbd58> finished executing, sending ok as response
2015-09-17 22:18:00,182 [DEBUG @ async_session.py:send:133] 5263 - sending response to request 1: [1, 1, None, 'ok']
2015-09-17 22:18:00,182 [DEBUG @ msgpack_stream.py:send:36] 5263 - sent [1, 1, None, 'ok']
2015-09-17 22:18:00,182 [DEBUG @ base.py:send:113] 5263 - Sending 'b'\x94\x01\x01\xc0\xa2ok''
2015-09-17 22:18:00,182 [DEBUG @ session.py:handler:185] 5263 - greenlet <greenlet.greenlet object at 0x1093bbd58> is now dying...
2015-09-17 22:18:00,182 [DEBUG @ base.py:run:138] 5263 - Entering event loop
2015-09-17 22:18:00,183 [DEBUG @ msgpack_stream.py:_on_data:57] 5263 - waiting for message...
2015-09-17 22:18:00,183 [DEBUG @ msgpack_stream.py:_on_data:59] 5263 - received message: [1, 4, None, b'/var/folders/g3/9dw49b2d3mjd4_4qsgj1cglr0000gn/T/nvimrHIV7I/1']
2015-09-17 22:18:00,183 [DEBUG @ async_session.py:_on_response:95] 5263 - received response: None, b'/var/folders/g3/9dw49b2d3mjd4_4qsgj1cglr0000gn/T/nvimrHIV7I/1'
2015-09-17 22:18:00,183 [DEBUG @ session.py:response_cb:141] 5263 - response is available for greenlet <greenlet.greenlet object at 0x1093bb930>, switching back
2015-09-17 22:18:00,183 [DEBUG @ msgpack_stream.py:_on_data:57] 5263 - waiting for message...
2015-09-17 22:18:00,183 [DEBUG @ msgpack_stream.py:_on_data:59] 5263 - received message: [0, 2, b'specs', [b'/Users/Gabri/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete.py']]
2015-09-17 22:18:00,183 [DEBUG @ async_session.py:_on_request:86] 5263 - received request: b'specs', [b'/Users/Gabri/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete.py']
2015-09-17 22:18:00,183 [DEBUG @ session.py:_on_request:189] 5263 - received rpc request, greenlet <greenlet.greenlet object at 0x1093bbd58> will handle it
2015-09-17 22:18:00,183 [DEBUG @ host.py:_on_request:64] 5263 - calling request handler for "specs", args: "[b'/Users/Gabri/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete.py']"
2015-09-17 22:18:00,183 [DEBUG @ host.py:_on_request:66] 5263 - request handler for 'specs [b'/Users/Gabri/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete.py']' returns: [{'opts': {}, 'name': 'DeopleteInitializePython', 'sync': True, 'type': 'command'}, {'opts': {}, 'name': 'DeopleteMessages', 'sync': True, 'type': 'command'}]
2015-09-17 22:18:00,183 [DEBUG @ session.py:handler:179] 5263 - greenlet <greenlet.greenlet object at 0x1093bbd58> finished executing, sending [{'name': 'DeopleteInitializePython', 'opts': {}, 'sync': True, 'type': 'command'}, {'name': 'DeopleteMessages', 'opts': {}, 'sync': True, 'type': 'command'}] as response
2015-09-17 22:18:00,183 [DEBUG @ async_session.py:send:133] 5263 - sending response to request 2: [1, 2, None, [{'name': 'DeopleteInitializePython', 'opts': {}, 'sync': True, 'type': 'command'}, {'name': 'DeopleteMessages', 'opts': {}, 'sync': True, 'type': 'command'}]]
2015-09-17 22:18:00,184 [DEBUG @ msgpack_stream.py:send:36] 5263 - sent [1, 2, None, [{'name': 'DeopleteInitializePython', 'opts': {}, 'sync': True, 'type': 'command'}, {'name': 'DeopleteMessages', 'opts': {}, 'sync': True, 'type': 'command'}]]
2015-09-17 22:18:00,184 [DEBUG @ base.py:send:113] 5263 - Sending 'b'\x94\x01\x02\xc0\x92\x84\xa4name\xb8DeopleteInitializePython\xa4opts\x80\xa4sync\xc3\xa4type\xa7command\x84\xa4name\xb0DeopleteMessages\xa4opts\x80\xa4sync\xc3\xa4type\xa7command''
2015-09-17 22:18:00,184 [DEBUG @ session.py:handler:185] 5263 - greenlet <greenlet.greenlet object at 0x1093bbd58> is now dying...
2015-09-17 22:18:00,184 [DEBUG @ msgpack_stream.py:_on_data:57] 5263 - waiting for message...
2015-09-17 22:18:00,184 [DEBUG @ msgpack_stream.py:_on_data:62] 5263 - unpacker needs more data...
2015-09-17 22:18:00,184 [DEBUG @ base.py:_on_error:166] 5263 - EOF
2015-09-17 22:18:00,184 [DEBUG @ base.py:stop:149] 5263 - Stopped event loop
2015-09-17 22:18:00,184 [DEBUG @ base.py:run:140] 5263 - Exited event loop
```

**Comment by Shougo** [comment]
I have tested it in minimal .nvimrc and latest neovim and latest python3 module.
But I cannot reproduce it...

Questions:

* DeopleteEnable works?
* Please upload reproduce ways from Vim starting in more detail.
* Please upload the movie

**Comment by ahmedelgabri** [comment]
I managed to narrow this down. If I enable any of these plugins then the popup doesn't work [tern_for_vim](https://github.com/marijnh/tern_for_vim) or [vim-jsx](https://github.com/mxw/vim-jsx)

And here is a recording to prove my point https://asciinema.org/a/26576

**Comment by Shougo** [comment]
OK.  I get it.  It seems omni source feature problem.  I will search it.

**Comment by Shougo** [comment]
@ahmedelgabri I cannot reproduce the problem.  I think you need .tern-project in the directory.

**Comment by ahmedelgabri** [comment]
I do have a `.tern-project` file in my project folder and still have this problem.

**Comment by 7belrhalmia** [comment]
please put in your .nvimrc 

     autocmd FileType javascript setlocal omnifunc=tern#Complete

**Comment by ahmedelgabri** [comment]
@7belrhalmia Already have it

```vim
  aug omnicomplete
    au!
    au FileType css,sass,scss,stylus,less setl omnifunc=csscomplete#CompleteCSS
    au FileType html,htmldjango,jinja,markdown setl omnifunc=emmet#completeTag
    au FileType javascript,jsx setl omnifunc=tern#Complete
    au FileType python setl omnifunc=pythoncomplete#Complete
    au FileType xml setl omnifunc=xmlcomplete#CompleteTags
  aug END

```

**Comment by Shougo** [comment]
I think it is not deoplete problem.
You should check if omnifunc works by `<C-x><C-o>` mapping.

**Comment by ahmedelgabri** [comment]
@Shougo `<C-x><C-o>` works normally

**Comment by Shougo** [comment]
I will close the issue.
Because, I cannot reproduce it in minimal .nvimrc.
So I think it is not deoplete problem.

If you think it is deoplete problem, please create minimal .nvimrc to reproduce it.
Current your minimal .vimrc is not minimal.
And the reproduce ways are wrong.

**Comment by ahmedelgabri** [comment]
> Current your minimal .vimrc is not minimal.

What about the one [here](https://github.com/Shougo/deoplete.nvim/issues/44#issuecomment-141217126)? This one worked but when I used the plugin with other plugins it stopped working so I tried to debug that's when I posted [this](https://github.com/Shougo/deoplete.nvim/issues/44#issuecomment-141793900)

Anyway, here is my full [`.vimrc`](https://github.com/ahmedelgabri/dotfiles/blob/master/vim/vimrc.local) file. I'd appreciate if you can have a look maybe you can find the problem.

**Comment by Shougo** [comment]
> What about the one here? This one worked but when I used the plugin with other plugins it stopped working so I tried to debug that's when I posted this

It is not minimal.  Because, it does not contain tern_for_vim configuration.
And you must provide the reproduce ways using tern_for_vim.
tern_for_vim works in my environment.

So your provided information is insufficiency.

**Comment by ahmedelgabri** [comment]
Even with providing the full `.vimrc` full is still insufficient information?

**Comment by Shougo** [comment]
Yes.  Please provide minimal .vimrc to reproduce it.

**Comment by ahmedelgabri** [comment]
Then I assume that this will be enough, yes/no?

```vim
set runtimepath+=~/.vim/plugged/deoplete.nvim/
set runtimepath+=~/.vim/plugged/tern_for_vim/

let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_smart_case = 1

au FileType javascript,jsx setl omnifunc=tern#Complete
```

**Comment by ahmedelgabri** [comment]
BTW, I updated deoplete and just disabled vim-jsx and kept tern on and it's working now I think this fix worked https://github.com/Shougo/deoplete.nvim/commit/d7e4bd9dcbb8bc2244c578295943d6d905180003 so the problem now after the update is not tern anymore it's vim-jsx

**Comment by Shougo** [comment]
> Then I assume that this will be enough, yes/no?

Yes.

> BTW, I updated deoplete and just disabled vim-jsx and kept tern on and it's working now I think this fix worked d7e4bd9 so the problem now after the update is not tern anymore it's vim-jsx

Please provide minimal .vimrc with vim-jsx and the reproduce ways.

**Comment by Shougo** [comment]
I have installed vim-jsx and tern_for_vim.  But it works.
I think it is not deoplete problem.

**Comment by wavded** [comment]
Seems to be a vim-jsx problem.  If I enable `let g:jsx_ext_required = 0` it breaks my JS file omnicompletion with tern.

**Comment by ahmedelgabri** [comment]
@wavded yes, that's true I forgot to update this issue. I opened an issue on `vim-jsx` now hopefully it will be fixed.

**Comment by ahmedelgabri** [comment]
@Shougo I wonder if [this](https://github.com/Shougo/deoplete.nvim/blob/4096c759ff2e05012330626ed5a4fb2b53fe0c96/doc/deoplete.txt#L81-L85) might fix the issue? Because in the `vim-jsx` issue I opened the owner mentioned https://github.com/mxw/vim-jsx/issues/68 that filetype matching might be the problem?

**Comment by Shougo** [comment]
OK.  I get it.  I will fix it.

**Comment by ahmedelgabri** [comment]
Great! thanks @Shougo

**Comment by Shougo** [comment]
Fixed.   Please test it.

**Comment by ahmedelgabri** [comment]
@Shougo still broken for me when I do `let g:jsx_ext_required = 0`

**Comment by Shougo** [comment]
Fixed.
Please test it again.

**Comment by ahmedelgabri** [comment]
Still not working for me.

**Comment by Shougo** [comment]
What's your problem?
You must need set `let g:jsx_ext_required = 0`.

**Comment by ahmedelgabri** [comment]
`let g:jsx_ext_required = 1` needs to be set to `let g:jsx_ext_required = 0` not `1` see [here](https://github.com/mxw/vim-jsx#usage) and I have the `autocmd` set properly.

**Comment by Shougo** [comment]
Ummmm...
I'm confusing.

> @Shougo I wonder if this might fix the issue? Because in the vim-jsx issue I opened the owner mentioned mxw/vim-jsx#68 that filetype matching might be the problem?

I have fixed the filetype matching problem.
But, you have the problem exists...

> @Shougo still broken for me when I do let g:jsx_ext_required = 0

Please create new issue and read the CONTRIBUTING.md.

Closing.

**Comment by Shougo** [comment]
@ahmedelgabri You said `g:jsx_ext_required = 0` is broken, it is OK.  But your report is no minimal init.vim and no minimal reproduce ways, no expected/current information.

**Comment by Shougo** [comment]
Fixed it.
