### ISSUE TITLE
Merlin (OCaml) fuzzy completion, duplicate entries

### ISSUE THREAD

**Issue by alexozer** [Shougo/deoplete.nvim#465]
# Problems summary
Fuzzy matching does not seem to work when the omnicomplete source is Merlin, and duplicate entries in the completions menu are produced.

## Environment Information

 * deoplete version(SHA1): 9a3c2ec8b464bcd4e840c565c45f2d67464c2eed

 * OS: Arch Linux

 * neovim version: 0.1.7

 * `:CheckHealth` result(neovim ver.0.1.5-452+):

```markdown
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - WARNING: "deoplete.nvim" is not registered.
  - WARNING: Out of date
    - SUGGESTIONS:
      - Run `:UpdateRemotePlugins`

## terminfo
  - INFO: key_backspace terminfo entry: key_backspace=\177,

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.6.0
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider
  - ERROR: Missing Neovim RubyGem
    - SUGGESTIONS:
      - Install or upgrade the neovim RubyGem using `gem install neovim`.
  - INFO: Ruby Version: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
  - INFO: Host Executable: not found
  - INFO: Host Version: not found
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
call plug#begin('~/.local/share/nvim')
Plug 'Shougo/deoplete.nvim'
call plug#end()

set rtp+=$HOME/.opam/4.04.0/share/merlin/vim

let g:deoplete#enable_at_startup = 1
call deoplete#custom#set('_', 'matchers', ['matcher_full_fuzzy'])
let g:deoplete#omni#input_patterns = {}
"let g:deoplete#omni#input_patterns.ocaml = '[.\w]+'
let g:deoplete#omni#input_patterns.ocaml = '.*'

" Uncomment below to test manual completion
"let g:deoplete#disable_auto_complete = 1
"imap <silent><expr><Tab> deoplete#mappings#manual_complete()
```

### Fuzzy matching

 1. Set up ocaml 4.04.0 with opam: `opam init -a -y --comp 4.04.0`
 2. Open vim and set the ocaml filetype
 3. Try completing `List.fold_left` with `List.fdl`

### Duplicate entries
1. Set up environment just like with fuzzy matching
2. Type `List.fold`, then backspace, observe duplicates
3. Uncomment end of minimal vimrc to test manual completion
4. Type `List.fold<tab><tab>`, observe duplicates
5. Delete line and type `List.fold<tab>`, observe duplicates persist
6. Type `List.fold<c-x><c-o>`, backspace until `List.fold`, observe no duplicates

## Screen shot (if possible)
![screenshot](http://i.imgur.com/ycVOsCA.png)

**Comment by abdullaev** [comment]
Same problem. It is not only with an external completion but also with snippets.

**Comment by alexozer** [comment]
@abdullaev which issues do you also see with snippets?

**Comment by jabui** [comment]
#461

**Comment by Shougo** [comment]
OK.  I get the problem.
It is bug.

**Comment by monkoose** [comment]
I can confirm duplication in python, D and lua files(so i guess everywhere and some problem with deoplete itself).
But they are do not popup at first suggestion, for appearing you need delete previously completion(and sometimes leave insert mode) and then you will have duplication for every word.

**Comment by alexozer** [comment]
@Shougo could you also reproduce the lack of fuzzy matching specifically with Merlin? For example it seems like fuzzy matching with that config works with python/jedi somehow

**Comment by Shougo** [comment]
Fixed.

**Comment by alexozer** [comment]
@Shougo thanks for fixing the duplication issue! I still see the fuzzy completion issue however on my end, maybe it should be a separate issue?

**Comment by Shougo** [comment]
It should be the different issue.

**Comment by Shougo** [comment]
I have tested.

> @Shougo thanks for fixing the duplication issue! I still see the fuzzy completion issue however on my end, maybe it should be a separate issue?

But I cannot reproduce the behavior.

The screenshot is here
![screenshot from 2017-04-14 11-19-22](https://cloud.githubusercontent.com/assets/41495/25031408/aec2097e-2107-11e7-8fd5-9f3c6e813ac6.png)

**Comment by Shougo** [comment]
My tested vimrc:

```vim
filetype plugin indent on

set rtp+=~/.cache/dein/repos/github.com/Shougo/deoplete.nvim/
set rtp+=~/.opam/4.04.0/share/merlin/vim/

let g:deoplete#enable_at_startup = 1
call deoplete#custom#set('_', 'matchers', ['matcher_full_fuzzy'])
let g:deoplete#omni#input_patterns = {}
"let g:deoplete#omni#input_patterns.ocaml = '[.\w]+'
let g:deoplete#omni#input_patterns.ocaml = '.*'

" Uncomment below to test manual completion
"let g:deoplete#disable_auto_complete = 1
"imap <silent><expr><Tab> deoplete#mappings#manual_complete()
```

What's wrong?
Please describe it more clearly.

**Comment by alexozer** [comment]
@Shougo ah, it appears the fuzzy problems are more nuanced than I
originally thought. New steps to reproduce:

1. Uncomment the <tab> manual completion lines
2. Open a new vim, set filetype to ocaml, and try completing
`List.fdrt<tab>` (for `List.fold_right`)
3. `List.fold_right` should not appear
4. Reopen a new vim again
5. Try completing `List.<tab>`, then escape and delete the line
6. Try completing `List.fdrt<tab>`
7. Observe `List.fold_right` appearing

So, it seems to only work after you also try to complete `List.<tab>`,
which I suppose normally occurs in autocomplete mode, but not necessarily
in manual complete mode.

**Comment by alexozer** [comment]
@Shougo ah, it appears the fuzzy problems are more nuanced than I originally thought. New steps to reproduce:

1. Uncomment the <tab> manual completion lines
2. Open a new vim, set filetype to ocaml, and try completing `List.fdrt<tab>` (for `List.fold_right`)
3. `List.fold_right` should not appear
4. Reopen a new vim again
5. Try completing `List.<tab>`, then escape and delete the line
6. Try completing `List.fdrt<tab>`
7. Observe `List.fold_right` appearing

So, it seems to only work after you also try to complete `List.<tab>`, which I suppose normally occurs in autocomplete mode, but not necessarily in manual complete mode.

**Comment by Shougo** [comment]
I will check the behavior.
But the omni fuzzy completion is very hacky.
Because, the omnifunc does not support it.  It is deoplete hack feature.
I may cannot resolve the problem.

**Comment by alexozer** [comment]
Thanks!
