### ISSUE TITLE
Manual completion setup / cursor gets moved to the left

### ISSUE THREAD

**Issue by blueyed** [Shougo/deoplete.nvim#72]
I am using the following config to trigger deoplete manually:
```
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#disable_auto_complete = 1
  inoremap <expr> <Tab>  deoplete#mappings#manual_complete()
```

This works in general, but will move the cursor one column to the left when completing, and displays the following message (which might trigger an hit-enter prompt if it's too long for the window):
> :call rpcnotify(g:deoplete#_channel_id, 'completion_begin',  deoplete#init#_context(    'Manual',[]))

It also does not select/advance to the next entry on successive presses of `<Tab>`. 

For this, the following mappings work:

    inoremap <expr> <Tab>  pumvisible() ? "\<C-n>" : deoplete#mappings#manual_complete()
    inoremap <expr> <S-Tab>  pumvisible() ? "\<C-p>" : "\<S-Tab>"

I might integrate it with SuperTab, but tried to keep it simple in the beginning.

**Comment by Shougo** [comment]
Fixed the documentation.  Thanks.

**Comment by blueyed** [comment]
@Shougo 
Have you tried it with `let g:deoplete#disable_auto_complete = 1`?

I am still seeing the cursor being moved to the left.

**Comment by Shougo** [comment]
@blueyed I cannot reproduce it.
Please read the CONTRIBUTING.md.

https://github.com/Shougo/deoplete.nvim/blob/master/CONTRIBUTING.md

**Comment by blueyed** [comment]
@Shougo 
Could not reproduce with a minimal Vim, but found out that it's caused by lazy-loading of [cursorcross](https://github.com/mtth/cursorcross.vim):

    NeoBundle 'mtth/cursorcross.vim'
            \, { 'autoload': { 'insert': 1, 'filetypes': 'all' } }

`NeoBundleReinstall cursorcross` fixed it.

Thanks!

**Comment by Shougo** [comment]
OK.

**Comment by raidiant** [comment]
:+1:  @blueyed 
The `inoremap <expr> <Tab>  pumvisible() ? "\<C-n>" : deoplete#mappings#manual_complete()`
fixed the problems I was having with my mapping.
Thanks a bunch.
