### ISSUE TITLE
[feature] Support prefixed Source OR input_prefix

### ISSUE THREAD

**Issue by balta2ar** [Shougo/deoplete.nvim#759]
Hello! Let me start with a demo of a deoplete Source that I rely heavily on, and which I use many times a day. I have a text file `jira.candidates.tsv` that looks like this:
```
OFFICE_IT-1257  Fix hg hook in cs/rnd-tests repo        Resolved        user1   2018-02-27
IT_SUPPORT-236  Configure certificates on https://someurl.company.net   Resolved        user2   2018-03-02
IT_DEV-319      Hypertext links to Crucible reviews in RT comments      On Hold <NA>    2018-03-12
GENERAL-1874    Re: changes for 2018 (high level summary)       New     <NA>    2018-03-10
DEMO-56 my test Open    user3   2018-03-06
ACCESS-6092     Please create bot user for SecretProject <-> TopSecretProject interaction       Resolved        user4   2018-03-05
ACCESS-2432     wrong permissions in test project. user1        Resolved        user1   2018-02-27
```
Now, deoplete Source uses this file to show completions for ticket numbers (first column) querying them by the title. See:
![deoplete-prefixed-completion](https://user-images.githubusercontent.com/340676/40074498-767a6440-5882-11e8-9af1-b43beb692da9.gif)

As you can see, the common pattern is this: `<prefix><query_string>`. However, filtering should ignore the `<prefix>` part. Finally, deoplete should filter by `abbr` but insert `word`.

Here is my code that implements the completer: https://gist.github.com/balta2ar/0e0216bee6f1a6c9e177f8abb60f7b69

It's not the cleanest code ever, but that's not the point. I see several downsides to this approach:
1. A lot of boilerplate on the user side for a simple filtering.
2. I have to filter results myself because I want to ignore `<prefix>` part. That's why I have to use `volatile` + `on_post_filter`.

I can give several examples where I could use such Source:
1. Ticket number completion that I have demonstrated above.
2. HG/Git branch/tip number completion, e.g.: `HG<branch_query>`
3. URL completion from browser, e.g.: `URL<uql_query>`
4. Process ID completion, e.g.: `PID<command_line_query>`

and many others. The point is that it seems to be a very common pattern for these types of Sources.

Could you please add some kind of support for such Sources so that it's easier for the Source author to write them?

Maybe I'm doing something wrong and there is a way to tell deoplete to ignore `input_pattern` when filtering candidates? Please give advice if it is so.

**Comment by Shougo** [comment]
@balta2ar 
https://github.com/Shougo/deoplete.nvim/pull/764

Ping.

**Comment by balta2ar** [comment]
@Shougo Thank you! I'm trying to figure out how to correctly use it, but I'm not sure I fully understand. Here is my experimental plugin for this feature: https://github.com/balta2ar/deoplete-matcherkey/blob/master/rplugin/python3/deoplete/sources/matcherkey.py

Are you suggesting that I should add custom key that is prefixed with complete_str? Is that the correct way to do that? I wish Source didn't have to add complete_str to the key, it could be a bit simpler for the Source author.

```python
def get_jira_candidates(current_prefix):
    # current_prefix == context['complete_str']
    candidates = [line.split('\t')[:2]
                  for line in JIRA_CANDIDATES.strip().splitlines()]
    return [{'word': ticket,
             'abbr': ticket + ' ' + title,
             'custom_key': current_prefix + title, }
            for ticket, title in candidates]
```

Also, I noticed two problems:
1. Menu does not always show up when I continue typing the pattern. I've seen something similar earlier. Is it related to caching? Can this be fixed? 
2. If I type `Space` and then `Backspace`, menu reappears but it reappears not filtered with the current pattern.

![deoplete-matcherkey-weird-caching-no-filtering](https://user-images.githubusercontent.com/340676/40278149-53eee990-5c34-11e8-8c0a-ee6f47c57cfd.gif)

**Comment by balta2ar** [comment]
> :help deoplete-options-refresh_always

I've tried setting it, but it does not help. The menu still does not appear. I'm testing on the following minimal configuration:

```vim
set nocompatible
call plug#begin('~/.vim/plugged')
Plug 'nixprime/cpsm'
Plug 'Shougo/deoplete.nvim'
Plug 'balta2ar/deoplete-matcherkey'
call plug#end()

filetype plugin indent on
syntax enable

"call deoplete#custom#option('auto_refresh_delay', 0)
call deoplete#custom#option('refresh_always', v:true)
call deoplete#custom#option('num_processes', 0)

let g:deoplete#enable_at_startup = 1
```

> You need to set is_volatile = True in the source.

When I set it to true, my results are not filtered and I always see full list of candidates in the menu. I'm not filtering by my own in `gather_candidates` (but I'm setting up matcher to cpsm in `__init__`). Isn't volatile required for plugins that do their own filtering? My plugin always returns the full list of candidates.

> The source doesn't have to set the prefix.

If I don't add `complete_str` to the `custom_key`, nothing is displayed in the menu.

**Comment by Shougo** [comment]
> Isn't volatile required for plugins that do their own filtering? My plugin always returns the full list of candidates.

If so, it is not required.  It is for source filtering.

**Comment by Shougo** [comment]
I will test it later.

Please upload the reproduce instructions from neovim starting.
If not, I will ignore your issue unfortunately.

**Comment by balta2ar** [comment]
> So you must disable the matcher(matcher_cpsm).

In the `__init__`? Why? What if I need fast fuzzy filtering along with `matcher_key`?

> Please upload the reproduce instructions from neovim starting.

They are simple, just use my minimal vimrc configuration (with this experimental Source `balta2ar/deoplete-matcherkey`) and start neovim. Start typing "HGcreatebot" (menu does not always show up while I type it). Try hitting Space and Backspace.

![deoplete-matcherkey-no-menu](https://user-images.githubusercontent.com/340676/40283540-8b2537bc-5c88-11e8-875d-952fbcf3ddc5.gif)

**Comment by Shougo** [comment]
> In the __init__? Why? What if I need fast fuzzy filtering along with matcher_key?

You should understand matcher mechanism....
I have not much time to explain it.
If you use matcher_cpsm, you must set `complete_str` matched prefix.
It is matcher_cpsm feature.

**Comment by Shougo** [comment]
> The problem with menu and caching seems to be similar to this: #763

The problem is fixed on HEAD.

**Comment by Shougo** [comment]
I will merge the feature on weekend.

**Comment by balta2ar** [comment]
Another issue is that current filter is not applied after hitting backspace:
![deoplete-does-not-refilter-after-backspace](https://user-images.githubusercontent.com/340676/40966012-fd7c8280-68b7-11e8-89db-1952dd6bce0a.gif)

**Comment by Shougo** [comment]
> Is it possible to set smartcase and ignorecase per Source?

No.  You cannot.

> Could you please check why call deoplete#custom#option('smart_case', v:false) has no effect with matcher_cpsm?

This is bug of deoplete matcher_cpsm.  I have fixed it.

> Another issue is that current filter is not applied after hitting backspace when deleting spaces from the right side of the input string:

You need to map `<BS>` and `<C-h>` like this.

```vim
" <C-h>, <BS>: close popup and delete backword char.
inoremap <expr><C-h> deoplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS> deoplete#smart_close_popup()."\<C-h>"
```

Because the default `<BS>` and `<C-h>` does not work deoplete filter.

**Comment by balta2ar** [comment]
> This is bug of deoplete matcher_cpsm. I have fixed it.

Thanks, it's working now!

> You need to map <BS> and <C-h> like this

I have updated deoplete to the latest version (with your recent commits) and added your example to vimrc, but it still shows all the candidates. Could this be a bug as well?

**Comment by balta2ar** [comment]
@Shougo I'm trying to come up with an integration test to make it easier for you to reproduce issues. I'm using this framework: https://github.com/inkarkat/runVimTests

Test setup is like this:
``` vim
set rtp+=~/.vim/plugged/deoplete.nvim
set rtp+=./plugins/deoplete-matcherkey

call deoplete#custom#option('num_processes', 0)
call deoplete#custom#option('smart_case', v:false)
call deoplete#custom#option('ignore_case', v:true)

inoremap <expr><C-h> deoplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS> deoplete#smart_close_popup()."\<C-h>"

inoremap <silent><expr> <TAB>
\ pumvisible() ? "\<C-n>" :
\ <SID>check_back_space() ? "\<TAB>" :
\ deoplete#mappings#manual_complete()
function! s:check_back_space() abort "{{{
let col = col('.') - 1
return !col || getline('.')[col - 1]  =~ '\s'
endfunction"}}}

let g:deoplete#enable_at_startup = 1
autocmd InsertEnter * call deoplete#enable()
call deoplete#enable()
call deoplete#initialize()
autocmd VimEnter * call deoplete#initialize()
```

In the test itself I'm trying to print something and select the first item from deoplete menu. The question is, how do I programmatically call deoplete and select the first item? Here is the test:
``` vim
"normal :UpdateRemotePlugins()<cr>

normal! iHGcreatebot
"execute "normal! i\<tab>"

call deoplete#manual_complete()
call deoplete#close_popup()

call vimtest#SaveOut()
call vimtest#Quit()
```
However, it prints an error message:
```
Error detected while processing function deoplete#manual_complete[1]..deoplete#is_enabled[1]..deoplete#init#_is_handler_enabled:                                              
line    1:                                                                                                                                                                    
E121: Undefined variable: s:is_handler_enabled                                                                                                                                
E15: Invalid expression: s:is_handler_enabled
```

**Comment by balta2ar** [comment]
I've tried this:
``` vim
call feedkeys("iHGcreatebot\<TAB>", 't')
```
but it does not seem to insert anything into the editor after the test...

**Comment by Shougo** [comment]
> In the test itself I'm trying to print something and select the first item from deoplete menu. The question is, how do I programmatically call deoplete and select the first item? Here is the test:

You cannot.  It is waste of time.
You should know deoplete is asynchronous completion framework.

I have said "please create the new issue".

**Comment by Shougo** [comment]
It is not bug of deoplete.
Your mistake.
